ALTER TABLE invites ADD COLUMN IF NOT EXISTS responder_name TEXT;
ALTER TABLE invites ADD COLUMN IF NOT EXISTS guests_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE invites ADD COLUMN IF NOT EXISTS message TEXT;
