import type { Metadata } from "next";
import Link from "next/link";
import PublicChrome from "../components/PublicChrome";

export const metadata: Metadata = { title: "About Family Weather", description: "Why Family Weather was created and how it helps people plan ordinary activities and important gatherings around real weather.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <PublicChrome><main className="publicMain"><section className="publicHero"><p className="publicKicker">Why Family Weather exists</p><h1>The forecast was available.<br /><em>The useful answer wasn’t.</em></h1><p>Family Weather began with a simple family problem: a day can look fine on paper and still be wrong for what everybody intends to do.</p></section><section className="aboutStory"><div><h2>It started with real plans.</h2><p>A pool day can become a chase for napkins, foil, and containers when the wind picks up. A cookout can move its dining indoors while the cooking stays outside. A family gathering can send guests through heavy rain when waiting an hour would have made the drive easier.</p><p>A normal forecast reports temperature, precipitation, and wind. The person planning still has to decide what those numbers mean for yard work, grilling, a birthday, a wedding, or people traveling to an unfamiliar address.</p></div><aside><strong>Family Weather asks a different question:</strong><p>What are you doing, where are you doing it, and when is the weather most suitable for that particular plan?</p></aside></section><section className="aboutValues"><article><span>01</span><h2>Useful before impressive</h2><p>The answer should help somebody make a decision, not bury them in meteorological decoration.</p></article><article><span>02</span><h2>Honest about uncertainty</h2><p>A forecast can change. Historical patterns are not predictions. Family Weather labels the source and limits of the information it provides.</p></article><article><span>03</span><h2>Built for ordinary people</h2><p>You should not need to be a weather expert or professional event planner to choose a reasonable time and communicate it to other people.</p></article></section><section className="publicClosing"><h2>Check the plan. Keep the people together.</h2><div className="publicActionRow"><Link className="publicPrimary" href="/plan">Plan around the weather <span>→</span></Link><a className="publicSecondary" href="/contact">Contact Family Weather</a></div></section></main></PublicChrome>;
}
