import type { Metadata } from "next";
import Link from "next/link";
import PublicChrome from "../components/PublicChrome";

export const metadata: Metadata = { title: "How Family Weather Works", description: "See how Family Weather turns forecasts and five-year weather history into useful activity and event-planning guidance.", alternates: { canonical: "/how-it-works" } };

export default function HowItWorksPage() {
  return <PublicChrome><main className="publicMain"><section className="publicHero"><p className="publicKicker">Forecast → decision → invitation</p><h1>Weather information<br /><em>with somewhere to go.</em></h1><p>Family Weather starts with the thing you intend to do. It then checks the place, date, setting, and relevant weather before giving you a planning window and an optional path to invite other people.</p><div className="publicActionRow"><Link className="publicPrimary" href="/plan">Try the planner <span>→</span></Link><Link className="publicSecondary" href="/weather-history">Explore weather history</Link></div></section><section className="processSteps">{[
    ["01", "Name the real activity", "Yard work and an outdoor wedding should not receive identical advice. Tell Family Weather what people will actually be doing."],
    ["02", "Search the real place", "Use an address, venue, landmark, city, postal code, or destination. Ambiguous names are resolved before the weather is checked."],
    ["03", "Choose the actual date", "Near-term plans use available forecasts. Farther-out plans use five years of matching-date history and are clearly labeled as historical guidance."],
    ["04", "Read the weather fit", "See a score, useful time window, temperatures, rain, wind, and plain-language considerations instead of interpreting a wall of numbers."],
    ["05", "Create an event if needed", "A personal activity can end with the answer. A gathering can continue into event details, invitation design, sharing, and RSVP management."],
  ].map(([number, title, copy]) => <article key={number}><span>{number}</span><div><h2>{title}</h2><p>{copy}</p></div></article>)}</section>
  <section className="answerAnatomy"><div><p className="publicKicker">What comes back</p><h2>The answer explains itself.</h2><p>You should not need a meteorology degree—or a second website—to understand what Family Weather found.</p></div><div className="answerAnatomyGrid"><article><small>WEATHER FIT</small><strong>0–100</strong><p>A quick summary of how well the selected conditions fit the activity and setting.</p></article><article><small>BEST WINDOW</small><strong>Useful hours</strong><p>The part of the day that makes the most sense when hourly information supports one.</p></article><article><small>CONDITIONS</small><strong>High · low · rain · wind</strong><p>The core facts stay visible so the recommendation never hides the weather behind it.</p></article><article><small>REASONS</small><strong>Plain language</strong><p>Short explanations tell you what looks manageable and what deserves another thought.</p></article></div></section>
  <section className="scenarioSection"><div><p className="publicKicker">Built from ordinary problems</p><h2>Plans rarely fail because somebody forgot the temperature.</h2></div><div className="scenarioGrid"><article><h3>Yard work</h3><p>Avoid doing the heaviest work during the hottest or coldest part of the day. The result can end there—no event or invitation required.</p></article><article><h3>Cookout</h3><p>Wind can disrupt the table even when grilling remains possible. The planner separates whether you can cook from whether everybody should dine outside.</p></article><article><h3>Guests traveling</h3><p>The weather at the destination can support a better arrival window. Each guest still handles the weather along their own route.</p></article><article><h3>Outdoor event</h3><p>Rain, wind, heat, and timing can change whether the original plan needs a backup, a new hour, or a different location.</p></article></div></section>
  <section className="publicClosing"><p className="publicKicker">Two clean stopping points</p><h2>Get the answer and leave—or turn it into an event.</h2><p>A personal plan stops after the weather fit. A gathering can continue into event details, invitation design, a shareable link, direct email delivery, and RSVP management.</p><div className="publicActionRow"><Link className="publicPrimary" href="/plan">Check a plan <span>→</span></Link><a className="publicSecondary" href="/create-event">Create an event</a></div></section>
  </main></PublicChrome>;
}
